#!/usr/bin/env python

import sys 
import functions as fc
vers = "0.02"



def guide():
    print "Python-Git" 
    print "pg     --version"
    print ""
    print ""
    print "       'init Project_name Language'       To start a new project in the currently founder"
    print "       'commit comment'                   To add a comment to your commit"
    print "       'add all'                          To add all local files to the currently selected project"
    print "       'proj'                             To see currently selected project"
    print "       'get_vers'                         To get all the commits made to the currently project"
    print "       'ls'                               To list all projects"
    print "       'change project_name'              To change to the selected project"
    print "       'get project_name'                 To list all project files"
    print ""

def parser(args):

    try:
        args_len = len(args) 
        opc = args[1]
        lst = args 
        if args_len == 1 : 
            print "Invalid input"
        else: 
            if (opc == 'init'):
                fc.init(args)
                    
            if (opc =='--version'):
                global vers
                print "Python Git Version:",vers
            elif (opc == 'get_vers') : 
                fc.get_vers()
            elif (opc == 'clone') : 
                fc.pg_clone(args)
            elif (opc == 'change'):
                fc.cng(args)
            elif (opc == 'commit'):
                fc.set_commit(args,args_len)
            elif (opc == 'ls') :
                fc.ls()
            elif (opc == 'get'):
                fc.get(args[2])
            elif (opc == 'add'):
                fc.add(args)
            elif (opc == 'push'):
                print fc.push(args)
            elif (opc == 'proj'):
                print fc.get_proj()
            elif (opc == 'guide'):
                guide()
    except IndexError: 
        guide()
        
if __name__ == '__main__': 
    args = sys.argv
    parser(args)
